# Generated by Django 3.2 on 2023-01-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
