# Generated by Django 3.2 on 2023-01-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20230117_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text_kg',
            new_name='text_tr',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_kg',
            new_name='title_tr',
        ),
    ]
