# Generated by Django 3.2 on 2023-01-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20230117_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text_tr',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_tr',
            new_name='title_ky',
        ),
    ]
