# Generated by Django 3.2 on 2023-04-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20230117_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
    ]
