# Generated by Django 3.2 on 2022-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_faculty_customer_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='book/pdfs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='book/photos/')),
            ],
        ),
    ]
