# Generated by Django 3.2 on 2022-12-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_auto_20221216_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/photos/'),
        ),
    ]
