# Generated by Django 3.2 on 2022-12-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_alter_chat_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Библотекар', 'verbose_name_plural': 'Библотекар'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультет'},
        ),
    ]
