# Generated by Django 3.2 on 2023-01-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_auto_20221226_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='image',
        ),
    ]
