# Generated by Django 3.2 on 2023-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_remove_chat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Инфо Ирбис',
                'verbose_name_plural': 'Инфо Ирбис',
            },
        ),
    ]
