# Generated by Django 3.2 on 2023-01-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0014_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-added'], 'verbose_name': 'Видеоуроки', 'verbose_name_plural': 'Видеоуроки'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
