# Generated by Django 3.2 on 2023-02-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_auto_20230123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
