# Generated by Django 3.2 on 2023-04-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0016_auto_20230201_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='title_ru',
        ),
    ]
