# Generated by Django 3.2 on 2022-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('l_body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('m_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('m_body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('os_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('os_body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('history_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('history_body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('history_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинки')),
            ],
            options={
                'verbose_name': 'О Библиотеке',
                'verbose_name_plural': 'О Библиотеке',
            },
        ),
    ]
