# Generated by Django 3.2 on 2022-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинки')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Картинки',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='library',
            name='history_body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст история'),
        ),
        migrations.AlterField(
            model_name='library',
            name='history_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинки история'),
        ),
        migrations.AlterField(
            model_name='library',
            name='history_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок история'),
        ),
        migrations.AlterField(
            model_name='library',
            name='l_body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о библиотеке'),
        ),
        migrations.AlterField(
            model_name='library',
            name='l_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок о библиотеке'),
        ),
        migrations.AlterField(
            model_name='library',
            name='m_body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст миссия'),
        ),
        migrations.AlterField(
            model_name='library',
            name='m_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок миссия'),
        ),
        migrations.AlterField(
            model_name='library',
            name='os_body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст основные зад'),
        ),
        migrations.AlterField(
            model_name='library',
            name='os_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок основные зад'),
        ),
    ]
