# Generated by Django 3.2 on 2023-01-17 04:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230109_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='text_kg',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='c_body_kg',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст каталог'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='c_body_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст каталог'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='c_title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок каталог'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='c_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок каталог'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_kg',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='library',
            name='history_body_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст история'),
        ),
        migrations.AddField(
            model_name='library',
            name='history_body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст история'),
        ),
        migrations.AddField(
            model_name='library',
            name='history_title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок история'),
        ),
        migrations.AddField(
            model_name='library',
            name='history_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок история'),
        ),
        migrations.AddField(
            model_name='library',
            name='l_body_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о библиотеке'),
        ),
        migrations.AddField(
            model_name='library',
            name='l_body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст о библиотеке'),
        ),
        migrations.AddField(
            model_name='library',
            name='l_title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок о библиотеке'),
        ),
        migrations.AddField(
            model_name='library',
            name='l_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок о библиотеке'),
        ),
        migrations.AddField(
            model_name='library',
            name='m_body_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст миссия'),
        ),
        migrations.AddField(
            model_name='library',
            name='m_body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст миссия'),
        ),
        migrations.AddField(
            model_name='library',
            name='m_title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок миссия'),
        ),
        migrations.AddField(
            model_name='library',
            name='m_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок миссия'),
        ),
        migrations.AddField(
            model_name='library',
            name='os_body_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст основные зад'),
        ),
        migrations.AddField(
            model_name='library',
            name='os_body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст основные зад'),
        ),
        migrations.AddField(
            model_name='library',
            name='os_title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок основные зад'),
        ),
        migrations.AddField(
            model_name='library',
            name='os_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок основные зад'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text_kg',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='readers',
            name='text_kg',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='readers',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='readers',
            name='title_kg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='readers',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='c_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст каталог'),
        ),
        migrations.AlterField(
            model_name='readers',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
