# Generated by Django 3.2 on 2023-01-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230117_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='text_kg',
            new_name='text_tr',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='title_kg',
            new_name='title_tr',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='c_body_kg',
            new_name='c_body_tr',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='c_title_kg',
            new_name='c_title_tr',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='text_kg',
            new_name='text_tr',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='title_kg',
            new_name='title_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='history_body_kg',
            new_name='history_body_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='history_title_kg',
            new_name='history_title_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='l_body_kg',
            new_name='l_body_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='l_title_kg',
            new_name='l_title_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='m_body_kg',
            new_name='m_body_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='m_title_kg',
            new_name='m_title_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='os_body_kg',
            new_name='os_body_tr',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='os_title_kg',
            new_name='os_title_tr',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='text_kg',
            new_name='text_tr',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title_kg',
            new_name='title_tr',
        ),
        migrations.RenameField(
            model_name='readers',
            old_name='text_kg',
            new_name='text_tr',
        ),
        migrations.RenameField(
            model_name='readers',
            old_name='title_kg',
            new_name='title_tr',
        ),
    ]
