# Generated by Django 3.2 on 2023-01-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230117_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='text_tr',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='title_tr',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='c_body_tr',
            new_name='c_body_ky',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='c_title_tr',
            new_name='c_title_ky',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='text_tr',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='title_tr',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='history_body_tr',
            new_name='history_body_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='history_title_tr',
            new_name='history_title_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='l_body_tr',
            new_name='l_body_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='l_title_tr',
            new_name='l_title_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='m_body_tr',
            new_name='m_body_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='m_title_tr',
            new_name='m_title_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='os_body_tr',
            new_name='os_body_ky',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='os_title_tr',
            new_name='os_title_ky',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='text_tr',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title_tr',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='readers',
            old_name='text_tr',
            new_name='text_ky',
        ),
        migrations.RenameField(
            model_name='readers',
            old_name='title_tr',
            new_name='title_ky',
        ),
    ]
