# Generated by Django 3.2 on 2023-01-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230117_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='text_ru',
        ),
    ]
