# Generated by Django 3.2 on 2023-01-23 09:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='readers',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='title_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readers',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
