# Generated by Django 3.2 on 2023-02-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_journal_newspaper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('-title',), 'verbose_name': 'Журнал', 'verbose_name_plural': 'Журнал'},
        ),
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ('-title',), 'verbose_name': 'Газета', 'verbose_name_plural': 'Газета'},
        ),
    ]
