# Generated by Django 3.2 on 2023-02-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230202_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('id',), 'verbose_name': 'Журнал', 'verbose_name_plural': 'Журнал'},
        ),
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ('id',), 'verbose_name': 'Газета', 'verbose_name_plural': 'Газета'},
        ),
    ]
