# Generated by Django 3.2 on 2023-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230203_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Информация')),
                ('image', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='', verbose_name='Картинки')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директор',
            },
        ),
        migrations.CreateModel(
            name='IBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Должность')),
                ('text', models.TextField(blank=True, verbose_name='Информация')),
                ('text1', models.TextField(blank=True, verbose_name='Полное Информация')),
                ('image', models.ImageField(blank=True, default='/profiles/profile1.png', null=True, upload_to='', verbose_name='Картинки')),
            ],
            options={
                'verbose_name': 'ИБО',
                'verbose_name_plural': 'ИБО',
            },
        ),
        migrations.RemoveField(
            model_name='ads',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='c_body_ky',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='c_body_ru',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='c_title_ky',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='c_title_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='history_body_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='history_body_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='history_title_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='history_title_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='l_body_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='l_body_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='l_title_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='l_title_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='m_body_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='m_body_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='m_title_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='m_title_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='os_body_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='os_body_ru',
        ),
        migrations.RemoveField(
            model_name='library',
            name='os_title_ky',
        ),
        migrations.RemoveField(
            model_name='library',
            name='os_title_ru',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='readers',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='readers',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='readers',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='readers',
            name='title_ru',
        ),
    ]
